# https://taskfile.dev

version: '3'

# FIXME: HOF_FMT_DISABLED is currently broken.
#   - See
#     - https://github.com/hofstadter-io/hof/blob/_dev/lib/fmt/fmtrs.go#L67
#   - PRs submitted:
#     - https://github.com/hofstadter-io/hof/pull/360
#     - https://github.com/hofstadter-io/hof/pull/361
# env:
#   HOF_FMT_DISABLED: 1

vars:
  OUTDIR: out

tasks:
  default:
    cmds:
      - task: gen
      - task: gen-convert

  gen:
    desc: Generate a document by combining data and a Go template.
    sources:
      - data.yaml
      - letter.txt.template
    generates:
      - "{{.OUTDIR}}/letter.txt"
    cmds:
      - hof gen data.yaml -T letter.txt.template=letter.txt -O {{.OUTDIR}}

  gen-convert:
    desc: Demonstrate data format conversion (e.g. yaml -> json).
    sources:
      - data.yaml
    generates:
      - "{{.OUTDIR}}/data.json"
    cmds:
      - hof gen data.yaml -T =data.json -O {{.OUTDIR}}

  clean:
    desc: Delete all output files.
    cmds:
      - rm -rf {{.OUTDIR}}
